#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Text-CSV
Version  : 1.96
Release  : 2
URL      : https://cpan.metacpan.org/authors/id/I/IS/ISHIGAKI/Text-CSV-1.96.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/I/IS/ISHIGAKI/Text-CSV-1.96.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libt/libtext-csv-perl/libtext-csv-perl_1.95-1.debian.tar.xz
Summary  : 'comma-separated values manipulator (using XS or PurePerl)'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-Text-CSV-license
BuildRequires : buildreq-cpan

%description
Text::CSV version 1.33
----------------------
Text::CSV provides facilities for the composition and decomposition of
comma-separated values.  An instance of the Text::CSV class can combine
fields into a CSV string and parse a CSV string into fields.

%package dev
Summary: dev components for the perl-Text-CSV package.
Group: Development
Provides: perl-Text-CSV-devel

%description dev
dev components for the perl-Text-CSV package.


%package license
Summary: license components for the perl-Text-CSV package.
Group: Default

%description license
license components for the perl-Text-CSV package.


%prep
%setup -q -n Text-CSV-1.96
cd ..
%setup -q -T -D -n Text-CSV-1.96 -b 1
mkdir -p deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Text-CSV-1.96/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-Text-CSV
cp deblicense/copyright %{buildroot}/usr/share/doc/perl-Text-CSV/deblicense_copyright
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Text/CSV.pm
/usr/lib/perl5/site_perl/5.26.1/Text/CSV_PP.pm

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Text::CSV.3
/usr/share/man/man3/Text::CSV_PP.3

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-Text-CSV/deblicense_copyright
